name: Build

on:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: ilammy/setup-nasm@v1.2.1
      - name: Update binaries
        run: |
          $ErrorActionPreference = 'SilentlyContinue'
          git clone --recursive https://github.com/N0N1m3/test-uws.git
          cd test-uws
          nmake
          git fetch origin binaries:binaries
          git checkout binaries
          xcopy /Y dist\*.node .
          git status
          git add *.node *.js
          git config --global user.email "n0n1m3.squad@gmail.com"
          git config --global user.name "N0N1m3"
          git commit -a -m "[GitHub Actions] Updated windows-latest binaries"
          git push "https://n0n1m3:${{ secrets.SECRET }}@github.com/n0n1m3/test-uws" binaries
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0, ubuntu-20.04]
    steps:
      - name: Update binaries
        run: |
          sudo xcode-select -switch /Applications/Xcode_12.2.app || true
          sudo apt update || true
          sudo apt install -y g++-aarch64-linux-gnu || true
          git clone --recursive https://github.com/N0N1m3/test-uws.git
          cd test-uws
          make
          git fetch origin binaries:binaries
          git checkout binaries
          cp dist/*.node .
          git status
          git add *.node *.js
          git rev-parse master > source_commit
          git checkout master docs/index.d.ts && mv docs/index.d.ts .
          git config --global user.email "n0n1m3.squad@gmail.com"
          git config --global user.name "N0N1m3"
          git commit -a -m "[GitHub Actions] Updated ${{ matrix.os }} binaries" || true
          git push "https://n0n1m3:${{ secrets.SECRET }}@github.com/n0n1m3/test-uws" binaries

  build-arm:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: aarch64
            os: ubuntu20.04
          - arch: armv7
            os: bullseye
    steps:
      - name: Clone
        run: git clone --recursive https://github.com/N0N1m3/test-uws.git
      - uses: uraimo/run-on-arch-action@v2.3.0
        name: Compile binaries
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.os }}
          dockerRunArgs: |
            --volume "${PWD}/test-uws:/repository"
          install: |
            apt-get update -q -y
            apt-get install -q -y build-essential cmake libz-dev golang curl libunwind-dev clang
          run: |
            cd /repository
            make
      - name: Update binaries
        run: |
          cd test-uws
          git fetch origin binaries:binaries
          git checkout binaries
          cp dist/*.node .
          cp dist/*.js .
          git status
          git rev-parse master > source_commit
          git checkout master docs/index.d.ts && mv docs/index.d.ts .
          git config --global user.email "n0n1m3.squad@gmail.com"
          git config --global user.name "N0N1m3"
          git add *.node *.js
          git commit -a -m "[GitHub Actions] Updated linux-${{ matrix.arch }} binaries" || true
          git push "https://n0n1m3:${{ secrets.SECRET }}@github.com/n0n1m3/test-uws" binaries
